use_frameworks!

platform :ios, '11.0'

target 'WDCloudMall_Example' do
  pod 'WDCloudMall', :path => '../'
  pod 'CryptoSwift', '~> 1.4.2'
  pod 'SnapKit', '~> 5.0.1'
  pod 'WechatOpenSDK', '1.8.7.1'

  target 'WDCloudMall_Tests' do
    inherit! :search_paths

    
  end
end
