use_frameworks!

platform :ios, '10.0'

target 'WDCloudMall_Example' do
  pod 'WDCloudMall', :path => '../'
  pod 'CryptoSwift', '~> 1.4.1'
  pod 'SnapKit', '~> 5.0.1'

  target 'WDCloudMall_Tests' do
    inherit! :search_paths

    
  end
end
